<?php

/**
 * @file Provides various VoIP Drupal Scripts for the Callblast
 */

foreach (array('callblast_scripts.scripts.inc') as $file) {
  require_once(dirname(__FILE__) . DIRECTORY_SEPARATOR . $file);
}

/**
 * Implementation of hook_menu().
 */
function callblast_scripts_menu() {
  $items['admin/voip/callblast_scripts'] = array(
    'title' => 'Callblast SMS prompts',
    'description' => 'Callblast SMS prompts.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('callblast_scripts_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function callblast_scripts_admin_settings_form() {
  $form['callblast_scripts_sms_help'] = array(
    '#type' => 'textarea',
    '#title' => t('SMS help'),
    '#description' => t('Text SMS help message'),
    '#default_value' => variable_get('callblast_scripts_sms_help',
      'Welcome to Callblast! To JOIN text any letter. To STOP receiving text messages, text "S". For HELP, text "H". Msg & data rates may apply.'),
);

  $form['callblast_scripts_sms_welcome'] = array(
    '#type' => 'textarea',
    '#title' => t('SMS welcome'),
    '#description' => t('Welcome SMS for text to be sent the first time a user subscribes to the service.'),
    '#default_value' => variable_get('callblast_scripts_sms_welcome', 'Welcome to Callblast App'),
  );

  $form['callblast_scripts_sms_unsubscribe'] = array(
    '#type' => 'textarea',
    '#title' => t('SMS Unsubscribe'),
    '#description' => t('Unsubscribe text for SMS to be sent when S command is received.'),
    '#default_value' => variable_get('callblast_scripts_sms_unsubscribe', 'You\'ve unsubscribed from the Callblast App and should not receive further messages. Should you choose to subscribe again, text any letter to this number.'),
  );

  $form['callblast_scripts_sms_duplicate'] = array(
    '#type' => 'textarea',
    '#title' => t('SMS Duplicate number'),
    '#description' => t('Text for SMS to be sent when number tries to register again. '),
    '#default_value' => variable_get('callblast_scripts_sms_unknown', 'Number already registered.'),
  );

  $form['callblast_scripts_sms_not_in_list'] = array(
    '#type' => 'textarea',
    '#title' => t('SMS Not in list'),
    '#description' => t('Text for SMS to be sent when number tries to unsubscribe but he is not registered. '),
    '#default_value' => variable_get('callblast_scripts_sms_not_in_list', 'Number not in the list.'),
  );

  $form['callblast_scripts_sms_unknown'] = array(
    '#type' => 'textarea',
    '#title' => t('Unknown command'),
    '#description' => t('SMS for unknown command.'),
    '#default_value' => variable_get('callblast_scripts_sms_unknown', 'Unknown command.'),
  );

  $form['callblast_scripts_opt_message'] = array(
    '#type' => 'textarea',
    '#title' => t('Opt-in message'),
    '#default_value' => variable_get('callblast_scripts_opt_message',
      'Callblast App would like to send you SMS reminders @ this number. X/week. H for help. S to end. Msg&data rates may apply. Reply J to confirm today.')
  );

  return system_settings_form($form);
}