<?php

foreach (array('pbb.scripts.inc') as $file) {
  require_once(dirname(__FILE__) . DIRECTORY_SEPARATOR . $file);
}

function _pbb_save_idea($idea_category, $idea_location, $idea_recording, $caller_number, $source) {
  watchdog('debug', "in _pbb_save_idea $idea_category, $idea_location, $idea_recording, $caller_number, $source");

  $node->type = 'ideas';
  $node->title = $idea_category.' at '.REQUEST_TIME;
  $node->language = 'und';
  $node->status = 1;
  $node->field_idea_category['und'][0]['value'] = $idea_category; //verify
  $node->field_caller_id['und'][0]['value'] = $caller_number;
  // create the node
  node_save($node);
  $nid = $node->nid;
  watchdog('debug', 'Idea saved '.$nid);

  $server = Voipserver::getServer($source);
  //$call = VoipCall::load($cid);
  $args = array(
    'nid' => $nid,
  );
  $server->audioFileMover($idea_location, '_pbb_save_idea_location', $args);
  $server->audioFileMover($idea_recording, '_pbb_save_idea_recording', $args);
}

function _pbb_save_idea_location($file, $recording_public_url, $args) {
  watchdog('debug', 'in _pbb_save_idea_location '.print_r($args,true));

  $node = node_load($args['nid']);
  $file->display = 1;
  $node->field_idea_location_audio['und'][0] = (array)$file;

  // update the node
  node_save($node);
  return $node;
}

function _pbb_save_idea_recording($file, $recording_public_url, $args) {
  watchdog('debug', 'in _pbb_save_idea_recording '.print_r($args,true));

  $node = node_load($args['nid']);
  $file->display = 1;
  $node->field_idea_description_audio['und'][0] = (array)$file;

  // update the node
  node_save($node);
  return $node;
}